version: '2.2'

services:
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    # ports:
    #   - 9200:9200
    networks:
      - esnet
  mariadb:
    image: 'mariadb'
    # ports:
    #   - 3306:3306
    env_file:
      - '.env'
      - '.env.production'
    volumes:
      - 'mariadb:/var/lib/mysql/'
    restart: on-failure
  redis:
    image: 'redis:3.2-alpine'
    # ports:
    #   - 6379:6379
    volumes:
      - 'redis:/var/lib/redis/data'
    restart: on-failure
    logging:
      options:
        max-size: 50m
  web:
    depends_on:
      - 'redis'
      - 'mariadb'
      - 'elasticsearch'
    #image: fuzzygroup/jobhoundsite_web
    build: .
    env_file:
      - '.env'
      - '.env.production'
    ports:
      - '3850:3850'
    restart: on-failure
    logging:
      options:
        max-size: 50m
  sidekiq:
    depends_on:
      - 'web'
    image: fuzzygroup/jobhoundsite_web
    env_file:
      - '.env'
      - '.env.production'
    command: "bundle exec sidekiq -C config/sidekiq.yml.erb"
    restart: on-failure
    logging:
      options:
        max-size: 50m
volumes:
  redis: {}
  mariadb: {}
  esdata1:
    driver: local
networks:
  esnet:
